name: CD Pipeline

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Authenticate Docker with GCP
      run: gcloud auth configure-docker

    - name: Build and push Docker image
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/latam-challenge:latest .
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/latam-challenge:latest

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy latam-challenge \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/latam-challenge:latest \
          --region ${{ secrets.GCP_REGION }} \
          --platform managed \
          --allow-unauthenticated
