name: "CI Pipeline"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Configurar Python y dependencias
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        make install

    # Ejecutar tests del modelo
    - name: Run model tests
      run: |
        source .venv/bin/activate
        make model-test

    # Ejecutar tests de la API
    - name: Run API tests
      run: |
        source .venv/bin/activate
        make api-test

    # Ejecutar tests de estrés
    - name: Run stress tests
      run: |
        source .venv/bin/activate
        make stress-test
